### ISSUE TITLE
Generic usage

### ISSUE THREAD

**Issue by psachin** [ervikrant06/virsh_xml_parser#7]
Can this package handle generic `virsh dumpxml` output like this?

[https://paste.fedoraproject.org/paste/EZQv5P6YhP4WRuIMGpgWW15M1UNdIGYhyRLivL9gydE=](https://paste.fedoraproject.org/paste/EZQv5P6YhP4WRuIMGpgWW15M1UNdIGYhyRLivL9gydE=)

Got following error
```
xmlvirshparser fedora-24-kernel.xml 
Traceback (most recent call last):
  File "/home/psachin/virtualenvs/python3-5/bin/xmlvirshparser", line 9, in <module>
    load_entry_point('xmlvirshparser==0.5', 'console_scripts', 'xmlvirshparser')()
  File "/home/psachin/virtualenvs/python3-5/lib/python3.5/site-packages/xmlvirshparser-0.5-py3.5.egg/xmlvirshparser/__init__.py", line 132, in main
  File "/home/psachin/virtualenvs/python3-5/lib/python3.5/site-packages/xmlvirshparser-0.5-py3.5.egg/xmlvirshparser/__init__.py", line 21, in extracting_vm_info
KeyError: 'sysinfo'
```

**Comment by ervikrant06** [comment]
@psachin Nope it can't because it's expecting nova related information which is missing from dumpxml. That information is only included with "virsh dumpxml" captured from openstack infra.
